import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import joblib
import os

class WindForecastingModel:
    def __init__(self):
        # Configure XGBoost regressor with tuned hyperparameters for noisy environmental data
        self.model = xgb.XGBRegressor(
            n_estimators=150,      # Number of gradient boosted trees
            max_depth=6,           # Maximum tree depth to capture non-linear interactions without overfitting
            learning_rate=0.05,    # Step size shrinkage to prevent overfitting during training
            subsample=0.8,         # Randomly sample 80% of data per tree to increase robustness
            colsample_bytree=0.8,  # Randomly sample 80% of features per tree to prevent dominant feature bias
            random_state=42        # Enforce reproducibility across training runs
        )
        # Dynamically resolve absolute path to persist/load model binary in the same directory as this module
        self.model_path = os.path.join(os.path.dirname(__file__), "wind_model.joblib")

    def engineer_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """Transforms raw weather parameters into high-signal ML features."""
        # Work on a copy of the DataFrame to prevent unintended side effects on caller's data
        df = df.copy()
        
        # Extract temporal features to capture diurnal (daily) and seasonal output variations
        df['hour'] = df['timestamp'].dt.hour
        df['month'] = df['timestamp'].dt.month
        
        # Transform 360° angular wind directions into continuous cyclic coordinates (sine and cosine)
        # This resolves boundary discontinuity (e.g., ensuring 359° and 1° are modeled as contiguous)
        df['wind_dir_sin'] = np.sin(np.radians(df['wind_direction']))
        df['wind_dir_cos'] = np.cos(np.radians(df['wind_direction']))
        
        # Create temporal lag features (1-hour and 2-hour historical wind speeds) to capture momentum
        df['wind_speed_lag1'] = df['wind_speed'].shift(1)
        df['wind_speed_lag2'] = df['wind_speed'].shift(2)
        
        # Drop initial rows containing NaN values generated by time-shifting (lagging)
        df = df.dropna().reset_index(drop=True)
        return df

    def train(self, df: pd.DataFrame):
        """Prepares data, executes training, and logs production validation metrics."""
        print("Starting Feature Engineering...")
        processed_df = self.engineer_features(df)
        
        # Isolate input feature columns (X) from the operational target column (y)
        feature_cols = ['wind_speed', 'temperature', 'hour', 'month', 
                        'wind_dir_sin', 'wind_dir_cos', 'wind_speed_lag1', 'wind_speed_lag2']
        X = processed_df[feature_cols]
        y = processed_df['actual_generation_mw']
        
        # Perform chronological split (shuffle=False) to preserve time series order and prevent temporal data leakage
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
        
        print(f"Training XGBoost Model on {len(X_train)} samples...")
        # Fit model on training set while passing test set for real-time validation monitoring
        self.model.fit(
            X_train, y_train,
            eval_set=[(X_test, y_test)],
            verbose=False
        )
        
        # Generate out-of-sample predictions on the holdout evaluation set
        predictions = self.model.predict(X_test)
        rmse = np.sqrt(mean_squared_error(y_test, predictions)) # Root Mean Squared Error (penalizes large errors)
        mae = mean_absolute_error(y_test, predictions)          # Mean Absolute Error (average error magnitude)
        r2 = r2_score(y_test, predictions)                      # Coefficient of determination (% variance explained)
        
        # Print formatted training metrics report
        print("\n" + "="*50)
        print("XGBOOST MODEL TRAINING COMPLETED")
        print("="*50)
        print(f"Root Mean Squared Error (RMSE):  {rmse:.3f} MW")
        print(f"Mean Absolute Error (MAE):       {mae:.3f} MW")
        print(f"Variance Score (R² Accuracy):    {r2 * 100:.2f}%")
        print("="*50)
        
        # Serialize and persist trained model artifact to disk
        joblib.dump(self.model, self.model_path)
        print(f"Model successfully saved to artifact: {self.model_path}\n")

    def predict_next_hour(self, current_weather_features: dict) -> float:
        """Accepts live production telemetry data and outputs a forward MW generation forecast."""
        # Guard clause: verify serialized model file exists before attempting inference
        if not os.path.exists(self.model_path):
            raise FileNotFoundError("Trained model artifact not found. Please train the model first.")
            
        # Load serialized model binary from storage
        loaded_model = joblib.load(self.model_path)
        
        # Convert incoming dictionary payload into a single-row Pandas DataFrame matching training schema
        input_df = pd.DataFrame([current_weather_features])
        
        # Run inference pass and extract target value scalar from 1D array result
        prediction = loaded_model.predict(input_df)
        return float(prediction[0])
      
